### ISSUE TITLE
Idea: filename structure

### ISSUE THREAD

**Issue by innicoder** [zhanymkanov/fastapi-best-practices#11]
#### Filename suggestion
Filenames inside the app/module specific can be example: `{module}_service.py`.
At some point it would be nice to create a generator for these like in django. 
`django startapp auth`.

#### Reason
We are already importing them `from src.auth import constants as auth_constants` it is easier to just change the filename so we don't have to keep track and it doesn't create any conflicts.

# PR - https://github.com/zhanymkanov/fastapi-best-practices/pull/12

#### Example
<img width="389" alt="image" src="https://user-images.githubusercontent.com/100089381/206858261-6891a3b7-2398-41f7-b8a6-7a717fc26001.png">

**Comment by zhanymkanov** [comment]
Hey, @innicoder, thank you for your proposal.

I believe it's not a great idea to duplicate the name of the package in the module's name, since we should assume that everything in that package is defacto related to that package and hereby doesn't need an explicit prefix of the package.

Importing the neighboring module within the package is the most frequent thing we would do, e.g. in the auth's `router` module we regularly use functions from the auth's `service` module. That would be unnecessary to call modules with an `auth` prefix since in the `auth.router` we mostly expect `auth.service` and nothing else. Having a longer name is redundant here.

But, if we have to import service from another package (which is a less probable thing to do since we try to keep packages loosely coupled), we would have to name it with an explicit package prefix.
