### ISSUE TITLE
How can i import from the src directory into package

### ISSUE THREAD

**Issue by tsalkenov** [zhanymkanov/fastapi-best-practices#18]
using sys.path.append in every file to access src doesn't seem like such a great idea to me. Maybe I'm doing it wrong i don't know a proper way to do this

**Comment by zhanymkanov** [comment]
It's ok when you have few packages, but once your project grows it's good to explicitly show that the package you are importing is local via `from src.notifications import client` rather than `from notifications import client`

**Comment by tsalkenov** [comment]
So there is no way to avoid using sys.path.append()?

**Comment by zhanymkanov** [comment]
I think the only reason you have to do that is improper project startup. You can check [this](https://github.com/zhanymkanov/fastapi_production_template) template. 

In short, I start projects from the root folder with `python -m src.main` so that interpreter knows the project boundaries and packages

**Comment by tsalkenov** [comment]
Oh i get it now, my interpreter was treating python files like they were separate. Now i get how it works thank you so much. Your this repository is a lifesaver. Thank you again for letting us learn from your experience
