### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by dimi-colossal** [zhanymkanov/fastapi-best-practices#42]
I'm fairly new to both Python and FastAPI, so I might be missing an obvious solution here. I joined a team that's already working with said stack and they've set up a dev Docker image that runs the app through uvicorn. I see a similar setup in your repo.

Coming from Java, I'd prefer to run and debug the application without the need to run it inside a container (and also setting up remote debugging looks like a pain). Why is there a preference to run it in a container? I tried following FastAPI's [suggested setup](https://fastapi.tiangolo.com/tutorial/debugging), but I quickly ran into some module import issues (probably due to my lack of deep Python understanding).

Any guidance on the reason for the design choice and possible bast practices would be welcome :)

**Comment by zhanymkanov** [comment]
Containers are great because they are easy to set up and run. Also, some networking isolation could be done, which is also nice. But, that is not an obligatory, nor a best practice - just a matter of choice.

If the module imports are not related to circular imports, then it is probably an improper server configuration. The best way that handles all the problems with it is to run the server from the project level, instead of the code level.

Here is the example:
```
- project/
-- src/
--- main.py
--- utils.py
```
If you attempt to run your code from the `src` directory using commands like `python -m main`, you are likely to encounter import issues with packages.

It's best to run the server from the project root directory, not from the `src` directory. Use the command `python -m src.main` from the `project/` directory rather than `python -m main` from the `src/` directory. This approach ensures that Python interprets your project structure correctly, resolving any import issues.

**Comment by WilliamStam** [comment]
we have 2 "main.py" files. 

<project>/main.py

```python
import multiprocessing
import os
import sys
import uvicorn

if __name__ == "__main__":
    os.chdir("src")
    cur_dir = os.path.dirname(__file__)

    sys.path.insert(0, os.getcwd())
    multiprocessing.freeze_support()
    uvicorn.run("app:app", reload=True, port=8000, reload_includes=["*.py", "*.jinja"])

```

then run it localy for dfev work (reload = true)

----

<project>/src/main.py
```python
import json

import uvicorn
import logging

from config import config
logger = logging.getLogger(__name__)


if __name__ == "__main__":
    if config.debug:
        logger.warning("DEBUG MODE")

    items = {
        "port": config.server.port,
        "host": config.server.interface,
        "workers": int(config.server.workers),
        "proxy_headers": True,
        "forwarded_allow_ips": "*",
    }
    logger.debug(json.dumps(items, indent=2))
    if config.server.ssl_keyfile:
        items["ssl_keyfile"] = config.server.ssl_keyfile
    if config.server.ssl_certfile:
        items["ssl_certfile"] = config.server.ssl_certfile

    uvicorn.run("app:app", **items)

```

even when running dockerf the entry point is the src/main.py but that loads it up in prod mode more or less. in future might move it out to be a single main.py but this works fine. (i dev on windows and deploy on linux so windows needs a few more options for multi processing)
